Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.48.130/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


server:
  servlet:
    context-path: /sell


#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:  sell.log

